### PR TITLE
Fix DevDiv 829965

### PR DESCRIPTION
**Pull request by amcasey**
Fix DevDiv #829965 - Part 1

This bug is making my life difficult, so I thought I'd chip in.  Unfortunately, there were too many yaks and I had to move on.  I believe this change fixes the issue, but when I ran the existing tests, I discovered some places where case-sensitivity was not plumbed through correctly.  That probably deserves more attention.  We also need new GTD and FAR tests, since those are apparently separate code paths.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
Did you mean to send the pull request to me?

**Comment by amcasey** [comment]
Yes.  It's not ready to be merged into upstream/master.

**Comment by jasonmalinowski** [comment]
Ah got it. So just consider this more as "if you fix this bug, you probably want to do something like this?"

**Comment by amcasey** [comment]
As I noted in my bug, I believe this change fixes the issue, but I didn't feel comfortable checking it in without more tests - especially since I found more bugs by running the existing tests.

**Comment by amcasey** [comment]
You should probably also interpret it as "please fix this bug". :)

**Comment by amcasey** [comment]
Now https://github.com/dotnet/roslyn/pull/3132

**Pull request closed without merging**
